name: Test script
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  install_ps_docker:
    runs-on: ubuntu-latest
    container: 
      image: ubuntu:latest
      volumes:
        - ${{ github.workspace }}:/tmp/install
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Run docker
       run: bash /tmp/install/install_percona --mode=ps || (cat install.log && exit 1)
